myfinance-web-dotnet/Models/ErrorViewModel.cs
namespace myfinance_web_dotnet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

myfinance-web-dotnet/Models/PlanoContaModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace myfinance_web_dotnet.Models
{
    public class PlanoContaModel
    {
        public int? Id {get; set;}
        public string Nome {get; set;}
        public string Tipo {get; set;}
    }
}

myfinance-web-dotnet/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Infrastructure;
using myfinance_web_dotnet.Models;

namespace myfinance_web_dotnet.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private MyFinanceDbContext _myFinanceDbContext;

    public HomeController(
        ILogger<HomeController> logger,
        MyFinanceDbContext myFinanceDbContext)
    {
        _logger = logger;
        _myFinanceDbContext = myFinanceDbContext;
    }

    public IActionResult Index()
    {
        var teste = _myFinanceDbContext.PlanoConta.FirstOrDefault();
        ViewBag.TESTE = teste.Nome;
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

myfinance-web-dotnet/Controllers/PlanoContaController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Domain;
using myfinance_web_dotnet.Infrastructure;
using myfinance_web_dotnet.Models;
using myfinance_web_dotnet.Services;

namespace myfinance_web_dotnet.Controllers
{
    [Route("[controller]")]
    public class PlanoContaController : Controller
    {
        private readonly IPlanoContaService _planoContaService;
        public PlanoContaController(IPlanoContaService planoContaService)
        {
            _planoContaService = planoContaService;
        }

        [Route("Index")]
        public IActionResult Index()
        {
            ViewBag.Lista = _planoContaService.ListarRegistros();
            return View();
        }

        [HttpPost]
        [HttpGet]
        [Route("Cadastro")]
        [Route("Cadastro/{id}")]
        public IActionResult Cadastro(PlanoContaModel? model, int? id)
        {
            if(id != null  && !ModelState.IsValid) // carregar registro em tela
            {
            var registro = _planoContaService.RetornarRegistro((int)id);
            
            var PlanoContaModel = new PlanoContaModel()
            {
                Id = registro.Id,
                Nome = registro.Nome,
                Tipo = registro.Tipo
            };
            return View(PlanoContaModel);
            }
            else if(model != null && ModelState.IsValid)
            {
                        
                    var planoConta = new PlanoConta
                    {
                        Id = model.Id,
                        Nome = model.Nome,
                        Tipo = model.Tipo
                    };

                    _planoContaService.Salvar(planoConta);

                    return RedirectToAction("Index");
 
            }
                else
                {
                return View();
                }
                
        }
        [HttpGet]
        [Route("Excluir/{id}")]
        public IActionResult Excluir(int id)
        {
            _planoContaService.Excluir(id);
            return RedirectToAction("Index");
        }


    }

}

myfinance-web-dotnet/Controllers/TransacaoController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using myfinance_web_dotnet.Infrastructure;
using myfinance_web_dotnet.Models;
using myfinance_web_dotnet.Services;

namespace myfinance_web_dotnet.Controllers
{
    public class TransacaoController : Controller
    {

        private readonly ITransacaoService _transacaoService;

        public TransacaoController(ITransacaoService transacaoService)
        {
            _transacaoService = transacaoService;
        }
        public IActionResult Index()
        {
        var listaTransacao = _transacaoService.ListarTransacoes();
        ViewBag.ListaTransacao = listaTransacao;

        return View();
        }

    }
}

myfinance-web-dotnet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

myfinance-web-dotnet/Views/PlanoConta/Cadastro.cshtml
@model PlanoContaModel

@{
    ViewData["Title"] = "Cadastro de Plano de Contas";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="PlanoConta" asp-action="Cadastro" method="post">
    <div class="container">
        <div class="mb-3">
            <label class="form-label">Descrição</label>
            <input type=hidden id="txtId" class="form-control" asp-for="Id" />
            <input type=text id="txtNome" class="form-control" asp-for="Nome" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label>@Html.RadioButtonFor(m => m.Tipo, "D")Despesa</label>
            <label>@Html.RadioButtonFor(m => m.Tipo, "R")Receita</label>
            <span asp-validation-for="Tipo" class="text-danger"></span>
        </div>

        <div class="mb-3">
           <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
           <button type="button" class="btn btn-secondary btn-lg" onclick="Voltar()">Cancelar</button>
        </div>
    </div>
</form>

<script>
    function Voltar()
    {
        window.location.href = "../PlanoConta/Index"
    }
</script>

myfinance-web-dotnet/Views/PlanoConta/Index.cshtml
@using myfinance_web_dotnet.Domain
@{
    ViewData["Title"] = "Plano de Contas";
}

<h1>Plano de Contas</h1>
<br />
<a type="button" class="btn btn-primary" asp-area="" asp-controller="PlanoConta" asp-action="Cadastro">Criar item de
    Plano de Conta</a>
<br /><br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Descrição</th>
        <th>Tipo</th>
        <th>#</th>
        <th>#</th>
    </tr>

    @{
        foreach (var item in (List<PlanoConta>)ViewBag.Lista)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Nome</td>
                <td>@item.Tipo</td>
                <td><button type="button" class="btn btn-warning" onclick="Editar(@item.Id)">Editar</button>
                </td>
                <td><button type="button" class="btn btn-danger" onclick="Excluir(@item.Id)">Excluir</button>
                </td>
            </tr>

        }
    }
</table>

<script>
    function Editar(id){
        window.location.href ="../PlanoConta/Cadastro/" + id; 
    }
    function Excluir(id){
        window.location.href ="../PlanoConta/Excluir/" + id; 
    }
</script>

myfinance-web-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - myfinance_web_dotnet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/myfinance_web_dotnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">myfinance_web_dotnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlanoConta" asp-action="Index">Plano de Contas</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacao" asp-action="Index">Transações Financeiras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - myfinance_web_dotnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

myfinance-web-dotnet/Views/Transacao/Index.cshtml
@using myfinance_web_dotnet.Domain
@{
    ViewData["Title"] = "Transações Financeiras";
}

<h1>Transacao</h1>
<br />
<a type="button" class="btn btn-primary">Registrar Transação</a>
<br /><br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Data</th>
        <th>valor</th>
        <th>Histórico</th>
        <th>Tipo</th>
        <th>PlanoConta</th>
        <th>#</th>
        <th>#</th>
    </tr>
    @{
        foreach (var item in (List<Transacao>)ViewBag.ListaTransacao)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Data</td>
                <td>@item.Valor</td>
                <td>@item.Historico</td>
                <td>@item.Tipo</td>
                <td>@item.PlanoContaId</td>
                <td><button type="button" class="btn btn-warning">Editar</button></td>
                <td><button type="button" class="btn btn-danger">Excluir</button></td>
            </tr>
        }
    }

    </tr>

</table>